Added build with prebuilt libs
EmbarkStudios/ash-molten pull request #33
Opened 2020-11-11 01:48 UTC by MarnixKuijs

Added the capability for building ash-molten with prebuilt libs of MoltenVK.

2020-11-11 14:02 UTC, repi requested changes
Nice!

Some notes

2020-11-11 14:02 UTC, repi commented on build.rs
> +        let target_dir = Path::new(&std::env::var("OUT_DIR").unwrap())
so this repurposes to existing `external` feature and re-uses it to download a pre-built library right? but that also means you can't provide your own if you have it (which is what the previous `external` feature meant).

May be cleanest to have 2 different features for this, like maybe `external-provided` and `external-downloaded` or something like that?

The `external-downloaded` and this case we should also add a separate CI build step that builds with that feature so we make sure it continues to work

2020-11-11 14:14 UTC, MarnixKuijs commented on build.rs
> +            .arg("download-prebuilt.sh")
Fair enough. I will just get rid of the .sh and just add commands to the build.rs

2020-11-11 14:15 UTC, MarnixKuijs commented on build.rs
> +        let target_dir = Path::new(&std::env::var("OUT_DIR").unwrap())
Good point. I will add a additional feature.

2020-11-12 21:56 UTC, repi requested changes
Tested locally and worked fine.

This looks good also, one small catch.

Also do think should add some brief comments about what the features do (including the default one) in `Cargo.toml` and also to README of the different modes, and some instructions on how to upload a new prebuilt MoltenVK library

2020-11-12 21:56 UTC, repi commented on .github/workflows/ci.yaml
> +          args: --features external -- -D warnings
This should just build the default feature also right? As CI can't build with the `external` feature as it doesn't have an externally provided MoltenVK?

```suggestion
          args: -- -D warnings
```

2020-11-12 22:04 UTC, MarnixKuijs commented on .github/workflows/ci.yaml
> +          args: --features external -- -D warnings
Ooh oops your are right

2020-11-12 22:07 UTC, MarnixKuijs commented
> Also do think should add some brief comments about what the features do (including the default one) in `Cargo.toml` and also to README of the different modes, and some instructions on how to upload a new prebuilt MoltenVK library

Good point I will add some

2020-11-13 22:10 UTC, merged