0.8.0+1.1.1
EmbarkStudios/ash-molten pull request #43
Opened 2021-01-11 18:31 UTC by MarnixKuijs

build.rs now deals with XCFrameworks properly. MoltenVK version upgrade to 1.1.1. Support for aarch64 version MoltenVK.

2021-01-12 14:25 UTC, MaikKlein commented on Cargo.toml
> +xcframework = { git = "https://github.com/EmbarkStudios/xcframework", branch = "main" }
Probably a good idea to pin this to a specific commit, or release a version of xcframework on crates.io.

2021-01-13 12:13 UTC, repi commented on Cargo.toml
> +xcframework = { git = "https://github.com/EmbarkStudios/xcframework", branch = "main" }
Not just a good idea, you have to publish that crate on crates.io in order to publish this crate on crates.io

2021-01-13 12:17 UTC, repi requested changes
The `xcframework` crate needs to be published for this to work and be merged.

Have you tested these changes on `aarch64-apple-darwin` also? As it changes the fairly complex loading I did before

2021-01-13 12:25 UTC, MarnixKuijs commented
Will be working on improving xcframework, before it can get published. So this commit will be on hold for now.

2021-01-25 11:49 UTC, VZout commented
Any chance we can update to MoltenVK latest instead of 1.1.1 for various rust-gpu related fixes?

2021-02-12 13:47 UTC, VZout commented
@MarnixKuijs Would you like some help on this PR? It's blocking me on a couple of issues.

2021-02-12 14:58 UTC, MarnixKuijs commented
@VZout yeah sure, the only thing that needs to happen is open sourcing https://github.com/EmbarkStudios/xcframework, but if that takes too much time you can also just take the code from that crate and add it to ash-molten.

2021-02-17 11:26 UTC, repi commented
Converting to draft until it works and is ready to be re-reviewed

2021-02-17 14:10 UTC, VZout commented
Spend a whole lot of time trying to figure out why the builds were failing turns out I exceeded the rate limit by my many commits. 🤦

2021-02-17 14:28 UTC, VZout commented on Cargo.toml
> +xcframework = { git = "https://github.com/EmbarkStudios/xcframework", branch = "main" }
Merged xcframework into ash-molten as a module.

2021-02-17 14:36 UTC, VZout commented
Merged `xcframework` into this repo as a module. Build fails because of Github API rate limiting.

2021-03-02 09:02 UTC, repi commented
Replaced by #45

2021-03-02 09:02 UTC, closed without merging